### ISSUE TITLE
Important changes to Free-IPTV

### ISSUE THREAD

**Issue by Free-IPTV** [linuxmint/hypnotix#124] opened 2021-04-03 05:32 UTC
Hi,

A new repo for Free IPTV will be available shortly. This repo is then a private repo!

What is the possibility that the Hypnotix app can then access this private repo?

With the current (still) public repo, a message appears and all m3u's are deleted.

Why this change? I'm getting tired of this stealing of our work! We do the work, look for new streams, look for the right logos, then make updates every day!

Others here at Github then use our work to enrich their repo or as a contributor! I really don't feel like doing it anymore!

Since you and the users of the Hypnotix app shouldn't have any disadvantages, I'll get in touch early enough.

See for yourself what's going on, something like that is already criminal rabble for me! 

https://github.com/iptv-org/iptv/pull/2324

https://github.com/iptv-org/iptv/pull/2322

https://github.com/iptv-org/iptv/pull/2320

https://github.com/iptv-org/iptv/pull/2282#issuecomment-808138484

We need another solution! This new solution should be available at the end of next week, until then there will be no more updates in the currently public repo.

**Comment by clefebvre** [comment] 2021-04-05 09:32
Hi,

I don't think hypnotix will be able to access a private repository.

I don't understand the problem though... you're saying people are committing/merging on your master branch even though you don't want them to?? Can't you administrate the access privileges to define exactly who can do that?

**Comment by Free-IPTV** [comment] 2021-04-05 10:02
Hi @clefebvre,

access rights in a public repo? How is that supposed to remain manageable. The Linux Minth team should still have access to my m3u's and we just have to find a way to go. 

If the APP is not accessed via a private repo, then maybe via a user account that I grant access to? Access via a server from you via SFTP, you will regularly receive my m3u's and updates. There are many options. 

I'm just tired of stealing our work all the time and it's a lot of work. Hypnotix should still have access!

**Comment by clefebvre** [comment] 2021-04-05 16:03
I don't know, I don't understand what the problem is... 

Your repository belongs to you right? Even though it's publicly viewable and forkable you can decide exactly who can push and merge to it.

You don't want people to fork the repository on github? is that the problem?

**Comment by Free-IPTV** [comment] 2021-04-05 16:19
I no longer provide a public repo, I have given the reasons. Surely there will be a solution how you can continue to use my needs. This has nothing to do with forks either.

**Comment by clefebvre** [comment] 2021-04-05 16:23
Ah I see, sorry I didn't initially understand the different repos. I thought iptv-org was your repository, not a fork.

**Comment by clefebvre** [comment] 2021-04-05 16:26
Does it matter though if people fork it? I mean, what harm does it do?

Hypnotix already has 54 forks. Cinnamon already has 600 forks, but it doesn't matter. Many of these forks are just backup copies made by people. Some are forks which are made to actually help and make pull requests, and very few actually develop into real forks which compete with our project. When they do (Ubuntu MATE for instance forked many of our tools and gathered some momentum), we still benefit since we can go and have a look at their improvements and cherry pick them.

In the end, it doesn't really harm us that people can fork our work, quite the opposite.

**Comment by Free-IPTV** [comment] 2021-04-05 16:37
> 
> 
> Ah I see, sorry I didn't initially understand the different repos. I thought iptv-org was your repository, not a fork.

Haha... IPTV-ORG, is just one of MANY who have used our work all the time and then publish it in their name and that is the end of it. Therefore no more public repo. Another big difference to IPTV-ORG and us, we only have legal streams. ;-)

**Comment by clefebvre** [comment] 2021-04-05 16:39
If the list goes private it will require some sort of authentication to access it. There are two solutions, neither of which really work.

**Solution 1**

We add the authentication information in hypnotix itself. Hypnotix is open-source though so anyone can see its source code, which would lead to anyone being able to access your private repository.

Not good.

**Solution 2**

You or we sync the m3u from your private repository to a public URL.
Hypnotix uses that public URL.
This means people still won't have access to your repository, but anyone will be able to download your M3U by looking at the address in the Hypnotix source code.

It's not good either because people who copy your work don't really care about your repository, they really care about the resulting M3U file. They'd still have access this way.

**Rationale**

If you make your repository private your project will die in my opinion.

- People who help in your private circle will eventually be busy or move to do other things and soon or later you'll be the only one maintaining this. When it's public, anyone can help. When it's private, eventually, nobody does.
- Even more concerning, if it's private, there will be less and less users. Soon or later you'll wonder why you do all this work if there are not a lot of users benefiting from it.

> Another big difference to IPTV-ORG and us, we only have legal streams

That's a huge thing for us.

**Comment by Free-IPTV** [comment] 2021-04-05 16:39
We should find a solution, no public access but access for Hypnotix. I think, we found a solution. ;-)

**Comment by Free-IPTV** [comment] 2021-04-05 16:45
> 
> 
> If the list goes private it will require some sort of authentication to access it. There are two solutions, neither of which really work.
> 
> **Solution 1**
> 
> We add the authentication information in hypnotix itself. Hypnotix is open-source though so anyone can see its source code, which would lead to anyone being able to access your private repository.
> 
> Not good.
> 
> **Solution 2**
> 
> You or we sync the m3u from your private repository to a public URL.
> Hypnotix uses that public URL.
> This means people still won't have access to your repository, but anyone will be able to download your M3U by looking at the address in the Hypnotix source code.
> 
> It's not good either because people who copy your work don't really care about your repository, they really care about the resulting M3U file. They'd still have access this way.
> 
> **Rationale**
> 
> If you make your repository private your project will die in my opinion.
> 
>     * People who help in your private circle will eventually be busy or move to do other things and soon or later you'll be the only one maintaining this. When it's public, anyone can help. When it's private, eventually, nobody does.
> 
>     * Even more concerning, if it's private, there will be less and less users. Soon or later you'll wonder why you do all this work if there are not a lot of users benefiting from it.
> 
> 
> > Another big difference to IPTV-ORG and us, we only have legal streams
> 
> That's a huge thing for us.

Okay, can i got a email-Address? Then we can talk about details per mail, not here. :-)

**Comment by clefebvre** [comment] 2021-04-05 16:47
Sure, root@linuxmint.com.

**Comment by Free-IPTV** [comment] 2021-04-05 16:49
> 
> 
> Sure, [root@linuxmint.com](mailto:root@linuxmint.com).

Great, i send you a mail! :-)

**Comment by matthuisman** [comment] 2021-04-10 10:46
@clefebvre
I'd be VERY concerned about working with the Free-IPTV playlist.
Basically he's taken free streams and is now trying to charge people to access them.
https://github.com/Free-IPTV/Countries/issues/289#issuecomment-817097251

**"Our Free-IPTV project is always a lot of work. We always have in the old repo
the streams are regularly updated and new streams offered free of charge.

Therefore we ask for a small donation. The donation is NOT for the streams, they are free, access to private repo also free.

The donation is for the daily work on the M3Us.** The donation is then always for 3 months and it is IMPORTANT that you include your username from Github with the donation so that I can assign it.

The minimum donation of 3 months is 3 EUR (1 EUR per month). NOT $ or other, only EUR please. Outside EUROPE 3,50 EUR (TAX PAYPAL). See it for us as an estimate for the immense work. I thank you!

It is of course voluntary, it should only be an appraisal of our work.

https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

After this process you will receive an invitation at your Github-Email with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

You will have the invitation and access new private repo by the latest next morning (Europe time). :-)

The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!"**

**Comment by Free-IPTV** [comment] 2021-04-10 13:47
@matthuisman 

_"now trying to charge people to access them."_

**This statement is wrong, do YOU ​​want to start a hate speech against me?**

This is standing in the text!

_"The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!"_

**Was the agitation against me in the forum in Australia not enough ???** 

Perhaps I will not let anyone into the closed repo for the time being, as a hate speech is now being started against me.

I have now deleted the text in the issue, now I no longer feel like it. For the time being, nobody is going to get into my new repo. I can say yes to the users, say thank you to Matt Huisman !!!

**The streams for Hypnotix users are free!!!** 

Matt what is this shit doing here, do you need THAT?

**Comment by Free-IPTV** [comment] 2021-04-10 14:03
HELLO HYPNOTIX TEAM!

**If Matt's agitation against me doesn't go away, it's END with the ZZ_PLAYLIST for Hypnotix !!!**

**Comment by Mennaruuk** [comment] 2021-04-10 14:19
Hello @Free-IPTV, may you please change your mind about this? This whole drama is putting me into a bad mood, I just want to watch TV when I go back from work. I’m confused: do we have to pay to see the channels? Or is the donation optional? Also, I think you can benefit from others who fork your project, maybe they have good legal streams too that you can cherry pick, and everybody is happy, just like how it’s with Linux Mint! Thank you very much, I wish you the best.

**Comment by Free-IPTV** [comment] 2021-04-10 14:27
> 
> 
> Hello @Free-IPTV, may you please change your mind about this? This whole drama is putting me into a bad mood, I just want to watch TV when I go back from work. I’m confused: do we have to pay to see the channels? Or is the donation optional? Also, I think you can benefit from others who fork your project, maybe they have good legal streams too that you can cherry pick, and everybody is happy, just like how it’s with Linux Mint! Thank you very much, I wish you the best.

I'm about to throw all that stuff away ... I'm tired of it, I am 61 years old, I no longer do the stress to myself!
Now the agitation against me is also going on at Github! NOGO!!!

**Comment by Mennaruuk** [comment] 2021-04-10 14:43
No please don’t delete the repo!!! 😢 😔

**Comment by Free-IPTV** [comment] 2021-04-10 14:52
> 
> 
> No please don’t delete the repo!!! cry pensive

@Mennaruuk 

Invitation is out, please leave the new readme there !!!

**Comment by Zhoro-111** [comment] 2021-04-10 15:43
> HELLO HYPNOTIX TEAM!
> 
> **If Matt's agitation against me doesn't go away, it's END with the ZZ_PLAYLIST for Hypnotix !!!**

And who is this guy Matt that can decide what others have to do???!!!!
Don't stress yourself about someone's comment that doesn't see it clearly or don't want to.Donations are always a pleasure for the hard work (Free or not Free).Maintening 4K streams is not same case of having 200-300 streams.
He has no idea for what reason you changed your repo to private and it's not the case to mention incomes because it's stupid to think that you done this change for money.I know better than him how many people you refused to get access and how many you payed back just to control the entries.He has no idea,that's why I don't care what he saying.He is no one to give directions,we are not his little kids.To finish it here I would say if people are gelaous I can't help them.Peace!!

**Comment by brainboyusa** [comment] 2021-04-10 16:38
> > No please don’t delete the repo!!! cry pensive
> 
> @Mennaruuk
> 
> Invitation is out, please read the new readme there !!! It comes with your Github Email!

Good afternoon. I have been using the M3U lines for personal use only, I not even had an account here until today. I don't really understand how these things work but I understand that only users already registered this all happened, will have access to the repo. It's really a shame that because of some stupid dishonest brat, honest users like me will lose access to the great list of legal channels. I completely understand your frustration, however, I'd really appreciate to be considered as a new member in case you would give me the opportunity. Many thanks.

**Comment by ItzSwirlz** [comment] 2021-04-10 21:22
The repos **must** be public. It's FOSS rule.

Also; can we all delete the spam? Calm down and stay on topic.

**Comment by Iangh59** [comment] 2021-04-10 23:17
I was one of the people who called him out on https://forums.whirlpool.net.au/forum/126. His response was to incite abuse against me, https://github.com/Free-IPTV/Countries/commit/d0b0981e4d1e4f85b5d38eeafc9e7c5aff5a6178. BTW, his Whirlpool thread was deleted for non-commercial advertising, https://postimg.cc/4mNfHRk4. Looks like he has gone one better and is now commercialising.:)

If you read his comments, it's always the other guy at fault who is attacking him. It's got nothing to do with his arrogance and petulance provoking a response. I like his lists, they are very convenient for a lot of people all over the world, I just wish he wasn't responsible for them. I don't understand his attitude - there's a lot of people who sniff streams and make them available without wanting/needing adoration. Grow up!

To those that list without requiring payment, a big thank you.

**Comment by JosephMcc** [comment] 2021-04-11 03:13
I'm locking this for now until @clefebvre or @mtwebster  decide it should be reopened. Things are getting nasty and no one needs that or benefits from it.

**Closed by JosephMcc** 2021-04-11 03:13 UTC
