### ISSUE TITLE
How about to mark some chanals to favorite list? (Feature Request)

### ISSUE THREAD

**Issue by IT-Tool** [linuxmint/hypnotix#102] opened 2021-01-31 15:45 UTC
Channel lists can be very long so I would like to add some to favorite list or to see the marked channels first in the list.

**Comment by Axel-Erfurt** [comment] 2021-01-31 21:37
You can create m3u from your favourite channels and import it then.

**Comment by DJCrashdummy** [comment] 2021-02-15 14:27
this is a duplicate of #36.

**Comment by Abu-Daud** [comment] 2021-03-01 17:25
I agree that this is a needed feature.  As a start, what about a way to pull the url of the currently playing stream to the clipboard or show it in a log file?

**Comment by clefebvre** [comment] 2021-04-11 12:41
This will happen. Closing the issue.

**Closed by clefebvre** 2021-04-11 12:41 UTC

**Comment by IT-Tool** [comment] 2021-09-27 22:44
duplicate of #126
